# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - appmak01

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://github.com/makroum1/test/blob/46ebdf560002dcab90935c453745aff9f2eaa185/test1.html/
        username: ${{ secrets.AzureAppService_ContainerUsername_7b2dc5555a1949e4a88a4ab0e46f7aea }}
        password: ${{ secrets.AzureAppService_ContainerPassword_52d08b224df9469bae0bfbfd49a6a2d9 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: github.com/makroum1/test/blob/46ebdf560002dcab90935c453745aff9f2eaa185/test1.html/${{ secrets.AzureAppService_ContainerUsername_7b2dc5555a1949e4a88a4ab0e46f7aea }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'appmak01'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_eb37fd06c0c9477197ad0457f3aef37e }}
        images: 'github.com/makroum1/test/blob/46ebdf560002dcab90935c453745aff9f2eaa185/test1.html/${{ secrets.AzureAppService_ContainerUsername_7b2dc5555a1949e4a88a4ab0e46f7aea }}/appsvc/staticsite:${{ github.sha }}'